# Generated by Django 3.2.7 on 2021-10-09 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('courses', models.ManyToManyField(related_name='children_of_course', to='courses.Courses', verbose_name='Курсы')),
                ('parent_of_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_of_parent', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
            },
        ),
    ]
