# Generated by Django 3.2.7 on 2021-10-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='children_of_course', to='courses.Courses', verbose_name='Курсы'),
        ),
    ]
