# Generated by Django 3.2.8 on 2021-10-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211009_1818'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='courses',
            field=models.ManyToManyField(related_name='children_of_courses', to='courses.Courses', verbose_name='Курсы'),
        ),
    ]
