<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-10-09 14:18
=======
# Generated by Django 3.2.7 on 2021-10-09 16:27
>>>>>>> bc1743eb307e4f3936acb72319cf1de7450175a4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('courses', '0003_auto_20211009_1818'),
=======
        ('courses', '0002_initial'),
>>>>>>> bc1743eb307e4f3936acb72319cf1de7450175a4
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='courses',
<<<<<<< HEAD
            field=models.ManyToManyField(related_name='children_of_courses', to='courses.Courses', verbose_name='Курсы'),
=======
            field=models.ManyToManyField(blank=True, related_name='children_of_course', to='courses.Courses', verbose_name='Курсы'),
>>>>>>> bc1743eb307e4f3936acb72319cf1de7450175a4
        ),
    ]
