# Generated by Django 3.2.8 on 2021-10-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Ребёнок', 'verbose_name_plural': 'Дети'},
        ),
    ]
