# Generated by Django 3.2.8 on 2021-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_alter_child_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Номер телефона'),
        ),
    ]
