# Generated by Django 3.2.8 on 2021-10-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_alter_child_parent_of_child'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentUser',
        ),
    ]
