# Generated by Django 3.2.8 on 2021-10-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_attendance_child'),
        ('parent', '0005_delete_parentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='courses',
            field=models.ManyToManyField(to='courses.Courses', verbose_name='Курсы'),
        ),
    ]
