# Generated by Django 3.2.7 on 2021-10-09 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_confirmed_parent', models.BooleanField(blank=True, default=False, verbose_name='Родитель подтвердил оплату')),
                ('paid_confirmed_teacher', models.BooleanField(blank=True, default=False, verbose_name='Преподаватель подтвердил оплату')),
                ('attendance_confirmed', models.BooleanField(blank=True, default=False, verbose_name='Преподаватель подтвердил посещение занятия')),
            ],
            options={
                'verbose_name': 'Посещаемость ученика',
                'verbose_name_plural': 'Посещаемость учеников',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назание курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('emoji', models.CharField(default='😀', max_length=255, verbose_name='Emoji')),
                ('number_of_hours', models.IntegerField(default=10, verbose_name='Количество часов')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_course', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название занятия')),
                ('description', models.TextField(verbose_name='Описание занятия')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('time', models.TimeField(verbose_name='Время занятия')),
                ('information', models.TextField(verbose_name='Информация о занятии')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_in_course', to='courses.courses', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
