# Generated by Django 3.2.7 on 2021-10-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_child', to='parent.child', verbose_name='Ребёнок'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_lessons', to='courses.lessons', verbose_name='Занятие'),
        ),
    ]
