# Generated by Django 3.2.7 on 2021-10-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='duration',
            field=models.TimeField(default='1:30', verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='price',
            field=models.IntegerField(default=500, verbose_name='Цена'),
        ),
    ]
