# Generated by Django 3.2.8 on 2021-10-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_child', to='parent.child', verbose_name='Ребёнок'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_lessons', to='courses.lessons', verbose_name='Занятие'),
        ),
    ]
