# Generated by Django 3.2.7 on 2021-10-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_teacher_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название занятия')),
                ('description', models.TextField(verbose_name='Описание занятия')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('time', models.TimeField(verbose_name='Время занятия')),
                ('information', models.TextField(verbose_name='Информация о занятии')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс')),
            ],
        ),
    ]
