# Generated by Django 3.2.7 on 2021-10-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lessons_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.teacher', verbose_name='Преподаватель'),
        ),
    ]
