# Generated by Django 3.2.8 on 2021-10-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_alter_child_parent_of_child'),
        ('courses', '0007_alter_courses_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='lessons',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parent.child', verbose_name='Ребёнок'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_confirmed_parent', models.BooleanField(blank=True, default=False, verbose_name='Родитель подтвердил оплату')),
                ('paid_confirmed_teacher', models.BooleanField(blank=True, default=False, verbose_name='Преподаватель подтвердил оплату')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessons', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Посещаемость ученика',
                'verbose_name_plural': 'Посещаемость учеников',
            },
        ),
    ]
