# Generated by Django 3.2.7 on 2021-10-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courses_emoji'),
        ('courses', '0009_auto_20211008_2223'),
    ]

    operations = [
    ]
