# Generated by Django 3.2.7 on 2021-10-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_courses_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_in_course', to='courses.courses', verbose_name='Курс'),
        ),
    ]
