# Generated by Django 3.2.8 on 2021-10-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_merge_20211009_1250'),
        ('courses', '0012_alter_lessons_course'),
    ]

    operations = [
    ]
