# Generated by Django 3.2.8 on 2021-10-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_merge_20211009_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='child',
        ),
    ]
