# Generated by Django 3.2.7 on 2021-10-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_merge_20211009_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='number_of_hours',
            field=models.IntegerField(default=10, verbose_name='Количество часов'),
        ),
    ]
