# Generated by Django 3.2.8 on 2021-10-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_delete_parentuser'),
        ('courses', '0013_merge_20211009_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='child',
        ),
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parent.child', verbose_name='Ребёнок'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lessons', to='courses.lessons', verbose_name='Занятие'),
        ),
    ]
