# Generated by Django 3.2.7 on 2021-10-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_merge_20211009_1313'),
        ('courses', '0014_courses_number_of_hours'),
    ]

    operations = [
    ]
