# Generated by Django 3.2.8 on 2021-10-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20211009_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Преподаватель подтвердил посещение занятия'),
        ),
    ]
