# Generated by Django 3.2.8 on 2021-10-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_courses_number_of_hours'),
        ('courses', '0014_remove_lessons_child'),
    ]

    operations = [
    ]
