# Generated by Django 3.2.8 on 2021-10-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_merge_20211009_1327'),
        ('courses', '0015_merge_20211009_1332'),
    ]

    operations = [
    ]
