# Generated by Django 3.2.7 on 2021-10-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_merge_20211009_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='child',
        ),
    ]
