# Generated by Django 3.2.8 on 2021-10-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_delete_parentuser'),
        ('courses', '0015_attendance_attendance_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_child', to='parent.child', verbose_name='Ребёнок'),
        ),
    ]
